# Imports datetime to define the DAG start date
from datetime import datetime

# Imports DAG class to create an Airflow workflow
from airflow import DAG

# Imports BashOperator to run shell/bash commands in Airflow tasks
from airflow.providers.standard.operators.bash import BashOperator

# Imports EmailOperator to send email notifications from Airflow
from airflow.providers.smtp.operators.smtp import EmailOperator

# Imports PythonOperator to run Python functions as Airflow tasks
from airflow.providers.standard.operators.python import PythonOperator

# Imports Path to handle file and folder paths safely
from pathlib import Path

# Imports yaml to read configuration values from a YAML file
import yaml

# Imports pandas to read, process, and write tabular data
import pandas as pd

# Path to the YAML configuration file
CONFIG_FILE = "/app/config/abba_baba_config.yaml"

# Opens and reads the YAML configuration file
with open(CONFIG_FILE, "r") as f:
    config = yaml.safe_load(f) # Converts the YAML file content into a Python dictionary

tree = config["tree_topology"] # Reads the tree topology value from the config file
output_dir = config["output_dir"] # Reads the output directory path from the config file

# Creates one string containing all VCF file paths separated by spaces
vcf_files = " ".join(
    f'"{config[i]["vcf_file"]}"'
    for i in ["P1", "P2", "P3", "Outgroup"] # Gets the VCF file path for P1, P2, P3, and Outgroup from the config file
)

# Function to create the SETS.txt file required by Dsuite
def write_sets_txt():
    output_file = Path(output_dir) / "SETS.txt"
    # Opens SETS.txt in write mode
    with open(output_file, "w", encoding="utf-8") as f:
        for i in ["P1", "P2", "P3", "Outgroup"]: # Loops through each group used in the ABBA-BABA analysis
            sample_id = config[i]["species_id"] # Gets the sample/species ID for the current group from the config file
            f.write(f"{sample_id}\t{i}\n") # Writes one line in the format: sample_id    group_name

# Function to create a clean text table from the Dsuite output
def create_tbl():
    # Reads the SETS_BBAA.txt file generated by Dsuite
    # sep=r"\s+" means columns are separated by one or more spaces
    df = pd.read_csv(Path(output_dir) / "SETS_BBAA.txt", sep=r"\s+", engine="python")

    headers = df.columns.tolist()
    row_data = df.iloc[0].astype(str).tolist()
    # Maps P1, P2, and P3 to their full species names from the config file
    species_map = {
        "P1": config["P1"]["species_name"],
        "P2": config["P2"]["species_name"],
        "P3": config["P3"]["species_name"],
    }
    # Replaces sample/group names in the row with actual species names
    for i, col in enumerate(headers):
        if col in species_map:
            row_data[i] = species_map[col]

    insert_pos = headers.index("P3") + 1
    headers.insert(insert_pos, "Outgroup")
    row_data.insert(insert_pos, config["Outgroup"]["species_name"])
    # Calculates the width needed for each column
    # This keeps the table neatly aligned
    col_widths = [max(len(str(h)), len(str(v))) for h, v in zip(headers, row_data)]
    # Creates a horizontal separator line for the table
    sep = "+" + "+".join("-" * (w + 2) for w in col_widths) + "+"

    def fmt(vals):
        return "| " + " | ".join(str(v).ljust(col_widths[i]) for i, v in enumerate(vals)) + " |"

    table = "\n".join([sep, fmt(headers), sep, fmt(row_data), sep])
    # Saves the formatted table into table.txt
    with open(Path(output_dir) / "table.txt", "w", encoding="utf-8") as f:
        f.write(table)

# Defines the Airflow DAG for the ABBA-BABA pipeline
with DAG(
    dag_id="abba_baba_pipeline", # Unique name for this DAG in the Airflow UI
    start_date=datetime(2026, 4, 14), # Date from which Airflow can start running this DAG
    schedule=None, # No automatic schedule; this DAG will run only when triggered manually
    catchup=False,  # Do not run missed/backdated DAG runs from the past
    tags=["abba-baba"],
) as dag:
    
    # Airflow task to index all VCF files before merging them
    index_vcfs = BashOperator(
        task_id="index_vcfs", # Task name shown in the Airflow UI
        # Bash commands that will run inside this task
        bash_command=f""" 
        set -e
        # Loops through each VCF file path stored in vcf_files
        for vcf in {vcf_files}; do
            # Checks if index file already exists
            if [ -f "$vcf.tbi" ]; then
                echo "Index already exists for $vcf, skipping"
            else
                bcftools index -t "$vcf"
            fi
        done """,
    )
    
    # Airflow task to merge all indexed VCF files into one compressed VCF file
    merge_vcfs = BashOperator(
        task_id="merge_vcfs", # Task name shown in the Airflow UI
        bash_command=f""" 
        # Merges all VCF files stored in vcf_files
        # -Oz means output should be compressed in .vcf.gz format
        # -o specifies the output file path
        bcftools merge {vcf_files} -Oz -o "{output_dir}/merged.vcf.gz" """,
    )

    # Airflow task to create an index file for the merged VCF file
    index_merged_vcf = BashOperator(
        task_id="index_merged_vcf", # Task name shown in the Airflow UI
        bash_command=f""" 
        # Creates a tabix index for the merged compressed VCF file
        # This will generate merged.vcf.gz.tbi
        bcftools index -t "{output_dir}/merged.vcf.gz" """,
    )

    # Airflow task to create the SETS.txt file needed by Dsuite
    create_sets_txt = PythonOperator(
        task_id="create_sets_txt", # Task name shown in the Airflow UI
        python_callable=write_sets_txt, # Python function that this task will run
    )

    # Airflow task to create the tree.nwk file needed by Dsuite
    create_tree_file = BashOperator(
        task_id="create_tree_file", # Task name shown in the Airflow UI
        bash_command=f""" 
        # Writes the tree topology from the config file into tree.nwk
        # tree.nwk is the Newick tree file used by Dsuite
        echo '{tree}' > "{output_dir}/tree.nwk" """,
    )

    # Airflow task to run the ABBA-BABA analysis using Dsuite
    run_dsuite_abba_baba = BashOperator(
        task_id="run_dsuite_abba_baba", # Task name shown in the Airflow UI
        bash_command=f"""
        # Runs Dsuite Dtrios for ABBA-BABA / introgression analysis
        # -t provides the Newick tree file
        # merged.vcf.gz is the merged input VCF file
        # SETS.txt tells Dsuite which sample belongs to P1, P2, P3, and Outgroup
        ~/Dsuite/Build/Dsuite Dtrios -t "{output_dir}/tree.nwk" "{output_dir}/merged.vcf.gz" \
        "{output_dir}/SETS.txt" """,
    )

    # Airflow task to create a readable table from the Dsuite output
    create_table = PythonOperator(
        task_id="create_table", # Task name shown in the Airflow UI
        python_callable=create_tbl, # Python function that this task will run
    )

    # Airflow task to send an email after the ABBA-BABA pipeline finishes successfully
    send_email = EmailOperator(
        task_id="send_email", # Task name shown in the Airflow UI
        # SMTP connection ID configured in Airflow
        # Airflow will use this connection to send the email
        conn_id="smtp_default", 
        # Email address of the person who should receive the notification
        # This value is read from the config file
        to=config['notify_to'],
        subject="ABBA-BABA analysis completed", # Subject line of the email
        html_content=f""" <h3>ABBA-BABA analysis completed successfully</h3> """, # Email body content in HTML format
    )


# Defines the order in which the Airflow tasks should run
# Each task starts only after the task before it completes successfully
index_vcfs >> merge_vcfs >> index_merged_vcf >> create_sets_txt >> create_tree_file >> run_dsuite_abba_baba >> create_table >> send_email