# Imports datetime to define the DAG start date
from datetime import datetime

# Imports DAG class to create an Airflow workflow
from airflow import DAG

# Imports BashOperator to run shell/bash commands in Airflow tasks
from airflow.providers.standard.operators.bash import BashOperator

# Imports EmailOperator to send email notifications from Airflow
from airflow.providers.smtp.operators.smtp import EmailOperator

# Imports Path to handle file and folder paths safely
from pathlib import Path

# Imports yaml to read configuration values from a YAML file
import yaml

# Path to the YAML configuration file
CONFIG_FILE = Path("/app/config/psmc_config.yaml")

# Opens and reads the YAML configuration file
with open(CONFIG_FILE, "r") as f:
    config = yaml.safe_load(f) # Converts the YAML file content into a Python dictionary

species_id = config["species_id"] # Reads the species ID from the config file
species_name=config["species_name"] # Reads the species name from the config file
vcf_file = config["vcf_file"] # Reads the input VCF file path from the config file
output_dir = config["output_dir"] # Read the output directory path from the config file
reference_genome = config["reference_genome"] # Reads the reference genome FASTA file path from the config file

# Reads the PSMC parameter values from the config file
# Example: N, t, r, and p values used by the psmc command
psmc_params = config["psmc_params"]
# Reads the plotting parameter values from the config file
# Example: mutation rate, generation time, max_y, min_x, and max_x
plot_params = config["plot_params"]

species_output_dir=f"{output_dir}/{species_id}" # To create a separate output folder path for this species
consensus_fa = f"{species_output_dir}/{species_id}.consensus.fa" # Path where the consensus FASTA file will be saved
psmcfa_file = f"{species_output_dir}/{species_id}.psmcfa" # Path where the converted PSMC input file will be saved
psmc_output = f"{species_output_dir}/{species_id}.psmc" # Path where the main PSMC result file will be saved
# Prefix used for the PSMC plot output files
# psmc_plot.pl will use this prefix to create files like .eps
plot_prefix = f"{species_output_dir}/{species_id}_plot"
plot_eps = f"{plot_prefix}.eps" # Path to the EPS plot file generated by psmc_plot.pl

# Defines the Airflow DAG for the PSMC pipeline
with DAG(
    dag_id="psmc_pipeline", # Unique name for this DAG in the Airflow UI
    start_date=datetime(2026, 4, 12), # Date from which Airflow can start running this DAG
    schedule=None, # No automatic schedule; this DAG will run only when triggered manually
    catchup=False, # Do not run missed/backdated DAG runs from the past
    tags=["psmc"],
) as dag:

    # Airflow task to index the reference genome FASTA file
    indexing_reference = BashOperator(
        task_id="indexing_reference", # Task name shown in the Airflow UI
        # Bash command to check and create the FASTA index
        bash_command=f""" 
            # Checks if the FASTA index file already exists
            if [ -f "{reference_genome}.fai" ]; then
                # If the index exists, skips indexing
                echo "FASTA index already exists: {reference_genome}.fai"
            else
                # If the index does not exist, creates it using samtools
                # This generates a .fai index file for the reference genome
                samtools faidx "{reference_genome}"
            fi """,
    )

    # Airflow task to index the input VCF file
    indexing_vcf = BashOperator(
        task_id="indexing_vcf", # Task name shown in the Airflow UI
        # Bash command to check and create the VCF index
        bash_command=f""" 
            # Checks if the VCF index file already exists
            if [ -f "{vcf_file}.tbi" ]; then
                # If the index exists, skips indexing
                echo "VCF index already exists: {vcf_file}.tbi"
            else
                # If the index does not exist, creates it using bcftools
                # -t creates a tabix index
                bcftools index -t "{vcf_file}"
            fi """,
    )

    # Airflow task to create a consensus FASTA file for the selected species
    make_consensus = BashOperator(
        task_id="make_consensus", # Task name shown in the Airflow UI
        # Bash command to create the output folder and generate the consensus FASTA
        bash_command=f""" 
        # Creates the species output directory if it does not already exist
        mkdir -p "{species_output_dir}" &&

        # Creates a consensus sequence using the reference genome and this species VCF file
        # -f provides the reference genome
        # -s selects the species ID from the VCF
        # -H I tells bcftools how to choose alleles for heterozygous sites
        # -M N replaces missing genotypes with N
        # The final output is saved into the consensus FASTA file
        bcftools consensus -f "{reference_genome}" -s "{species_id}" -H I -M N "{vcf_file}" > "{consensus_fa}" """,
    )

    # Airflow task to convert the consensus FASTA file into PSMC input format
    convert_to_psmc_input = BashOperator(
        task_id="convert_to_psmc_input", # Task name shown in the Airflow UI
        # Bash command to run fq2psmcfa and create the .psmcfa file
        bash_command=f""" 
        # Converts the consensus FASTA file into a PSMCFA file
        # -q20 filters out low-quality bases below quality 20
        # The output is saved into the psmcfa_file path
        ~/psmc/utils/fq2psmcfa -q20 "{consensus_fa}" > "{psmcfa_file}" """,
    )

    # Airflow task to run the PSMC analysis
    run_psmc = BashOperator(
        task_id="run_psmc", # Task name shown in the Airflow UI
        # Bash command to run PSMC using parameters from the config file
        bash_command=f""" 
        # Runs the PSMC program on the .psmcfa input file
        # -N sets the maximum number of iterations
        # -t sets the initial theta/rho ratio
        # -r sets the initial recombination/mutation rate ratio
        # -p sets the time interval pattern used by PSMC
        # -o sets the output .psmc file path
        ~/psmc/psmc -N{psmc_params['N']} -t{psmc_params['t']} -r{psmc_params['r']} \
        -p "{psmc_params['p']}" -o "{psmc_output}" "{psmcfa_file}" """,
    )

    # Airflow task to generate a PSMC plot from the PSMC output file
    plot_psmc = BashOperator(
        task_id="plot_psmc", # Task name shown in the Airflow UI
        # Bash command to run the PSMC plotting script
        bash_command=f"""
        # Generates a PSMC plot using psmc_plot.pl
        # -T sets the title of the plot
        # -u sets the mutation rate
        # -g sets the generation time
        # -Y sets the maximum value for the Y-axis
        # -x sets the minimum value for the X-axis
        # -X sets the maximum value for the X-axis
        # -m and -n are plotting options used by psmc_plot.pl
        # plot_prefix is the output file prefix
        # psmc_output is the input .psmc result file
        ~/psmc/utils/psmc_plot.pl -T "PSMC Analysis of {species_name}" -u {plot_params['mutation_rate']} \
        -g {plot_params['generation_time']} -Y {plot_params['max_y']} -x {plot_params['min_x']} \
        -X {plot_params['max_x']} -m 5 -n 0 "{plot_prefix}" "{psmc_output}" """,
    )

    # Airflow task to convert the PSMC plot from EPS format to PDF format
    convert_eps_to_pdf = BashOperator(
        task_id="convert_eps_to_pdf", # Task name shown in the Airflow UI
        # Bash command to convert the EPS plot file into a PDF file
        bash_command=f""" 
        # Converts the EPS plot generated by psmc_plot.pl into a PDF
        # This creates a PDF version of the same plot
        epstopdf "{plot_eps}" """,
    )

    # Airflow task to send an email after the PSMC pipeline finishes successfully
    send_email = EmailOperator(
        task_id="send_email", # Task name shown in the Airflow UI
        # SMTP connection ID configured in Airflow
        # Airflow will use this connection to send the email
        conn_id="smtp_default",
        # Email address of the person who should receive the notification
        # This value is read from the config file
        to=config['notify_to'],
        subject=f"PSMC pipeline completed for {species_id}", # Subject line of the email
        # Email body content in HTML format
        html_content=f""" <h3>PSMC pipeline completed successfully</h3>
        <p><b>Species ID:</b> {species_id}</p>
        <p><b>Species name:</b> {species_name}</p> """,
    )


# Defines the order in which the Airflow tasks should run
# Each task starts only after the task before it completes successfully
indexing_reference >> indexing_vcf >> make_consensus >> convert_to_psmc_input >> run_psmc>> plot_psmc >> convert_eps_to_pdf >> send_email