P1:
  species_id: "PD_0598"
  species_name: "Trachypithecus geei"
  vcf_file: "/app/inputs/psmc/PD_0598.variable.filtered.HF.snps.vcf.gz"
P2:
  species_id: "PD_0603"
  species_name: "Trachypithecus pileatus"
  vcf_file: "/app/inputs/psmc/PD_0603.variable.filtered.HF.snps.vcf.gz"
P3:
  species_id: "PD_0602"
  species_name: "Trachypithecus phayrei"
  vcf_file: "/app/inputs/psmc/PD_0602.variable.filtered.HF.snps.vcf.gz"  
Outgroup:
  species_id: "PD_0588"
  species_name: "Semnopithecus entellus"
  vcf_file: "/app/inputs/psmc/PD_0588.variable.filtered.HF.snps.vcf.gz"  

# Tree topology used by Dsuite
# This shows the relationship between P1, P2, P3, and the Outgroup
tree_topology: "(((P1,P2),P3),Outgroup);"
# Folder where ABBA-BABA outputs to be saved
output_dir: "/app/outputs/abba-baba"
# Email address that will receive pipeline completion notifications
notify_to : "your_email@example.com"

