# Species ID used for this SDM analysis
species_id: "PD_0588"
# Full scientific name of the species
species_name: "Semnopithecus entellus"
# Folder where SDM outputs to be saved
output_dir: "/app/outputs/sdm"
# Folder containing the IUCN mammal shapefiles
iucn_input: "/app/inputs/sdm/MAMMALS"
# Number of GBIF occurrence records to download
num_of_records_to_pull_from_gbif: 2000
# Folder containing WorldClim bioclimatic raster files
climate_data: "/app/inputs/sdm/wc2.1_2.5m_bio"
# Number of background points to generate for SDM modeling
num_of_background_points: 10000
# Select bioclimatic variables used for model training
bio_variables: ['bio1', 'bio3', 'bio5', 'bio6', 'bio8', 'bio9', 'bio12', 'bio16', 'bio17', 'bio18', 'bio19']
# Email address that will receive pipeline completion notifications
notify_to : "your_email@example.com"